### ISSUE TITLE
2024 Dec 9 - Protocol Team Kickoff

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/pm#11]
We are introducing a new protocol-team call to coordinate protocol work.

This call is focused on resolving immediate development coordination issues, not longer term upgrade planning.

Agenda:
- Quick project updates, focus on deconflicting time/work.
  - Holocene:
    - Mostly successful Sepolia upgrade
    - Reth incident, need for multi-client testing
    - Chain Upgrade Process follow-ups
  - Interop:
    - Split of reader and owned nodes, per [design doc](https://github.com/ethereum-optimism/design-docs/blob/main/protocol/supervisor-dataflow.md)
  - Isthmus upgrade:
    - changes since Isthmus sync (Dec 3)
    - Pectra debate; devnet proposal
- Platforms team work
  - Introducing Kurtosis testing over next few weeks
  - Devnet improvements
- Non-project updates
  - `op-geth` upstream 1.14.12, [PR by Roberto](https://github.com/ethereum-optimism/op-geth/pull/432).
  - `op-node` P2P req-resp plans
  - Transaction inclusion latency improvements together with Platforms team
  - Rebasing the force-batch API functionality of Conduit on the latest Batcher
- Introducing service-focused milestones to the monorepo: yay/nay?

**Comment by tynes** [comment]
Proposal for how to scope hardforks: https://oplabs.notion.site/External-How-to-Scope-Hardforks-151f153ee162805cad2ed2f6613ce058?pvs=4

I would like to propose a devnet based approach to shipping isthmus. Each feature must make it onto a devnet safely before considered for inclusion. There is certainly space for all existing features that we have already been considering to make it into a devnet. The devnet approach helps a lot in a multiclient world, so that we can make sure the feature works between clients before finalizing the scope of the hardfork. All clients/teams are invited to participate in these devnets. Just because there is a feature on the devnet, it doesn't mean that it must be promoted to the next hardfork

isthmus-devnet-0 Scope
Release: First half of January
Features:
  
Withdrawal root in block header
EIP-7702

And also operator fee, if @Succinct Labs is able to have it ready by that time

**Comment by protolambda** [comment]
Notes:

- Vinod working with Kurtosis to reproduce the chain-split
    - Can then reproduce this with op-nethermind.
        - Vinod to share testing approach with Swapnil Raj.
        - https://github.com/ethereum-optimism/optimism/issues/13192
    - Undetermined how we integrate Kurtosis in our process (CI / releases / etc.)
        - Need Kurtosis to be automated
- Holocene deployments prepared before Holidays, although with more manual steps still.
- Scoping Isthmus, devnet-based approach
    - Other teams should be able to work back from what the UX is
        - Make OPCM and op-deployer a must for Isthmus
    - Priority is still Holocene safety.
        - George/Seb can tap Vinod if necessary.
    - `revm` is being refactored
        - isthmus blocked in `revm` until end of month
    - Mid-January target for Isthmus devnet
- Non-project:
    - Seb and Proto to review the op-geth 1.14.12 upgrade
    - Proto to help make P2P req-resp fix actionable
    - Platforms team is owning scheduling/starting of tx-inclusion-time improvements
    - George to reach out to Conduit about force-batch API, maybe work with Sam from platforms.
- Service-focused release milestones
    - Going forward with this, just for op-node and op-batcher.
